"""Unit tests for the contrast-augmentation modules used to build views.

The contrastive views in CACD are generated by stacking gamma, bias-field,
and GIN/RandConv augmentations on the input image. Each module must:

* preserve input shape (the diffusion target uses the augmented view directly),
* return finite values (NaNs poison the contrastive loss silently),
* sample independent transforms on each forward call (otherwise N_augs
  views collapse to copies and the contrastive loss has nothing to push).

Tests are pure-CPU and use small inputs so the suite stays fast.
"""

from __future__ import annotations

import torch

from diffae.model.augmentations.bias_field import RandBiasFieldCorruptionAugmentation
from diffae.model.augmentations.rc_aug import RandConvAugmentation
from diffae.transforms import GammaAugmentation


def test_bias_field_preserves_shape_and_is_finite(fake_image_batch: torch.Tensor) -> None:
    aug = RandBiasFieldCorruptionAugmentation(
        img_size=fake_image_batch.shape[-2:],
        dims=2,
        bias_field_std=0.5,
        bias_scale=0.025,
    )
    out = aug(fake_image_batch)
    assert out.shape == fake_image_batch.shape
    assert torch.isfinite(out).all()


def test_bias_field_sample_n_transforms_distinct() -> None:
    """Each call to ``sample_n_transforms`` should produce independent
    transforms — applying two of them to the same input must yield
    different outputs (with overwhelmingly high probability)."""
    aug = RandBiasFieldCorruptionAugmentation(
        img_size=(32, 32), dims=2, bias_field_std=0.5, bias_scale=0.05
    )
    transforms = aug.sample_n_transforms(2, device=torch.device("cpu"), dtype=torch.float32)
    img = torch.rand(1, 1, 32, 32)
    out_a = transforms[0](img)
    out_b = transforms[1](img)
    assert not torch.allclose(out_a, out_b)


def test_gamma_preserves_shape_and_finite(fake_image_batch: torch.Tensor) -> None:
    aug = GammaAugmentation(gamma_std=0.5)
    # AdjustContrast expects nonneg input; shift to [0, 1].
    img01 = (fake_image_batch + 1.0) / 2.0
    out = aug(img01)
    assert out.shape == img01.shape
    assert torch.isfinite(out).all()


def test_gamma_sample_n_transforms_independent() -> None:
    aug = GammaAugmentation(gamma_std=0.5)
    transforms = aug.sample_n_transforms(4)
    assert len(transforms) == 4
    img = torch.rand(1, 1, 32, 32)
    outs = [t(img) for t in transforms]
    # Not all four sampled gammas should produce identical outputs.
    distinct = any(not torch.allclose(outs[0], o) for o in outs[1:])
    assert distinct


def test_rand_conv_gin_preserves_shape_and_finite(fake_image_batch: torch.Tensor) -> None:
    aug = RandConvAugmentation(
        spatial_dims=2,
        rc_type="gin",
        n_layers=2,
        n_hidden_chans=2,
        do_updownsampling=False,
        target_size=64,
    )
    out = aug(fake_image_batch)
    assert out.shape == fake_image_batch.shape
    assert torch.isfinite(out).all()


def test_rand_conv_gin_resamples_per_call(fake_image_batch: torch.Tensor) -> None:
    """Calling forward twice on the same input must produce different views;
    otherwise contrastive training degenerates to identical positive pairs."""
    aug = RandConvAugmentation(
        spatial_dims=2,
        rc_type="gin",
        n_layers=2,
        n_hidden_chans=2,
        do_updownsampling=False,
        target_size=64,
    )
    out_a = aug(fake_image_batch)
    out_b = aug(fake_image_batch)
    assert not torch.allclose(out_a, out_b)
